config/routes.rb
Rails.application.routes.draw do
  get 'stores/index'
  devise_for :users
  # root to: "meal_plans#new"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :meal_plans, only: [:new, :create, :show] do
    resources :grocery_lists, only: [:create, :index]
  end
  resources :meals, only: [:update, :destroy, :show] do
    member do
      patch "replace"
    end
  end
  resources :grocery_items, only: [:update] do
    member do
      patch "mark_as_bought"
    end
  end
  get "map", to: "grocery_lists#mapping", as: :map
  get "meal_plans_empty", to: "meal_plans#empty", as: :meal_plans_empty
  get "grocery_lists_empty", to: "grocery_lists#empty", as: :grocery_lists_empty
  get "mapping_empty", to: "grocery_lists#empty", as: :mapping_empty
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  MAX_NB_MEAL = 7

  belongs_to :user, optional: true
  has_many :meals, dependent: :destroy
  has_many :recipes, through: :meals
  has_many :grocery_items, dependent: :destroy
  has_many :ingredients, through: :grocery_items
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  def show
    @meal_plan = MealPlan.find(params[:id])
    @meals = Meal.includes(:meal_plan).where(meal_plan: { id: params[:id] })
  end

  def new
    @meal_plan = MealPlan.new
  end

  def create
    nb_meals = meal_plan_params[:nb_meals].to_i
    nb_people = meal_plan_params[:nb_people].to_i

    @meal_plan = MealPlan.new(user: current_user, name: "Menu du #{Time.now.strftime("%d %B %Y")}")

    forbidden_recipe_ids = Recipe.joins(:diets).where(diets: {id: params[:diets]}).distinct.ids
    filtered_recipes = Recipe.where.not(id: forbidden_recipe_ids)
    filtered_recipes = sampling_and_filling(nb_meals, filtered_recipes)

    @meal_plan.meals = filtered_recipes.map { |recipe| Meal.new(meal_plan: @meal_plan, recipe: recipe, nb_people: nb_people) }

    @meal_plan.preferences = {
      nb_meals: nb_meals,
      nb_people: nb_people,
      diets_ids: params[:diets]}

    if @meal_plan.save
      redirect_to meal_plan_path(@meal_plan)
    else
      render :new, status: 422
    end
  end

  def empty
  end

  private

  def sampling_and_filling(nb_meals, filtered_recipes)
    if nb_meals <= filtered_recipes.size
      filtered_recipes.sample(nb_meals)
    else
      nb_meals_done = filtered_recipes.size
      while nb_meals_done < nb_meals
        nb = [nb_meals - nb_meals_done, filtered_recipes.size].min
        filtered_recipes += filtered_recipes.sample(nb)
        nb_meals_done += nb
      end
      filtered_recipes
    end
  end

  def meal_plan_params
    params.require(:meal_plan).permit(:name, :user_id, :nb_meals, :nb_people)
  end
end

app/views/meal_plans/_diet_icons.html.erb
<div class="mealplan-form-diet-option">
  <input type="checkbox" class="mealplan-form-diet-checkbox" name="diets[]" id="<%= diet.id %>" value="<%= diet.id %>">
  <label for="<%= diet.id %>">
    <% case diet.name %>
    <% when "not_vegetarian" %>
      <span class="my-icon-vegetarian mealplan-form-diet-icon icon-stroke">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
          <g fill="none" sstroke-linejoin="round" stroke-width="2"><path stroke-linecap="round" d="M16 10H8c-2.188 0-3.698 1.415-3.935 3.282c-.325 2.56.529 4.105 3.634 5.128c1.394.46 2.579 1.464 3.01 2.868l.223.722l.095-.082a8 8 0 0 1 2.175-1.331l1.921-.789c3.286-1.348 5.22-3.408 4.826-6.516C19.712 11.415 18.188 10 16 10m-4.036-3.03s-3.075.306-4.685-1.035C5.669 4.593 6.036 2.03 6.036 2.03s3.075-.306 4.686 1.035c1.61 1.342 1.242 3.905 1.242 3.905"/><path stroke-linecap="round" d="M12.036 6.97s3.075.306 4.685-1.035c1.61-1.342 1.243-3.905 1.243-3.905s-3.075-.306-4.685 1.035c-1.61 1.342-1.243 3.905-1.243 3.905"/><path d="M19 11.5c-.5 1-3.134 1.5-7 1.5s-6.5-.5-7-1.5"/></g>
        </svg>
      </span>
    <% when "not_vegan" %>
      <span class="my-icon-vegan mealplan-form-diet-icon icon-stroke">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
          <g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M2 2a26.6 26.6 0 0 1 10 20c.9-6.82 1.5-9.5 4-14m0 0q6 0 6-6q-6 0-6 6"/><path d="M17.41 3.6a10 10 0 1 0 3 3"/></g>
        </svg>
      </span>
    <% when "lactose" %>
      <span class="my-icon-lactose-free mealplan-form-diet-icon icon-stroke">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
          <g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M8 2h8M9 2v1.343M15 2v2.789a4 4 0 0 0 .672 2.219l.656.984a4 4 0 0 1 .672 2.22v1.131M7.8 7.8l-.128.192A4 4 0 0 0 7 10.212V20a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-3"/><path d="M7 15a6.47 6.47 0 0 1 5 0a6.47 6.47 0 0 0 3.435.435M2 2l20 20"/></g>
        </svg>
      </span>
    <% when "gluten" %>
      <span class="my-icon-gluten-free mealplan-form-diet-icon icon-fill">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
          <path d="M11.96 1.21c-.66 1.55-1.32 3.1-1.31 4.61c.01.6.12 1.18.29 1.8a3.4 3.4 0 0 0-.27-.45C9.83 6 8.17 5 6.5 4c0 .8 0 1.59.18 2.36L13 12.68V10.7c1.5-.9 2.92-1.82 3.67-2.87c.83-1.16.83-2.5.83-3.83c-1.67 1-3.33 2-4.17 3.17c-.1.14-.18.28-.26.42c.18-.63.29-1.27.28-1.9c-.01-1.51-.7-3-1.39-4.48M3.28 5.5L2 6.77l4.64 4.64c.11.59.31 1.14.69 1.67c.75 1.05 2.17 1.97 3.67 2.87v2.28l-.33-.56c-.84-1.17-2.5-2.17-4.17-3.17c0 1.33 0 2.67.83 3.83c.75 1.05 2.17 1.97 3.67 2.87V23h2v-1.8c.74-.44 1.45-.89 2.07-1.36l3.66 3.66L20 22.22C14 16.23 9.1 11.32 3.28 5.5M17.5 9.25c-1.67 1-3.33 2-4.17 3.17l-.21.37L15 14.66c.67-.5 1.27-1.02 1.67-1.58c.83-1.16.83-2.5.83-3.83m0 5.25c-.57.34-1.12.68-1.65 1.03l1.44 1.44c.21-.8.21-1.64.21-2.47"/>
        </svg>
      </span>
    <% when "pork" %>
      <span class="my-icon-pork-free mealplan-form-diet-icon icon-stroke">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
          <path fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11v.01M10 6h1.499l4.5-3v3.803A6.02 6.02 0 0 1 18.657 10h1.341a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-1.342q-.085.24-.19.472M16.999 17v1.5a1.5 1.5 0 0 1-3 0v-.583a6 6 0 0 1-1 .083h-4a6 6 0 0 1-1-.083v.583a1.5 1.5 0 0 1-3 0v-2.027a6 6 0 0 1 1.5-9.928M3 3l18 18"/>
        </svg>
      </span>
    <% when "glucose" %>
      <span class="my-icon-sugar-free mealplan-form-diet-icon icon-stroke">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
          <g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="m8.5 8.5l-1 1a4.95 4.95 0 0 0 7 7l1-1m-3.657-9.313A4.95 4.95 0 0 1 16.5 7.5a4.95 4.95 0 0 1 1.313 4.657M14 16.5V14m0-7.5v1.843M10 10v7.5"/><path d="m16 7l1-5l1.367.683A3 3 0 0 0 19.708 3H21v1.292a3 3 0 0 0 .317 1.341L22 7l-5 1m-9 9l-1 5l-1.367-.683A3 3 0 0 0 4.292 21H3v-1.292a3 3 0 0 0-.317-1.341L2 17l5-1M2 2l20 20"/></g>
        </svg>
      </span>
    <% when "nuts" %>
      <span class="my-icon-nut-free mealplan-form-diet-icon icon-stroke">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
          <g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M12 4V2m-7 8v4a7.004 7.004 0 0 0 5.277 6.787c.412.104.802.292 1.102.592L12 22l.621-.621c.3-.3.69-.488 1.102-.592a7 7 0 0 0 4.125-2.939M19 10v3.343"/><path d="M12 12c-1.349-.573-1.905-1.005-2.5-2c-.546.902-1.048 1.353-2.5 2c-1.018-.644-1.46-1.08-2-2c-1.028.71-1.69.918-3 1c1.081-1.048 1.757-2.03 2-3c.194-.776.84-1.551 1.79-2.21m11.654 5.997c.887-.457 1.28-.891 1.556-1.787c1.032.916 1.683 1.157 3 1c-1.297-1.036-1.758-2.03-2-3c-.5-2-4-4-8-4c-.74 0-1.461.068-2.15.192M2 2l20 20"/></g>
        </svg>
      </span>
    <% when "sea_food" %>
      <span class="my-icon-seafood-free mealplan-form-diet-icon icon-fill">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
          <path d="m20.8 22.7l-5.1-5.1c-.6.7-1.1 1.3-1.6 1.7c-.8.7-1.4.7-2.1.7l.8-3c-3.3-.2-6.2-1.6-7-3.4c-.1.5-.2.9-.4 1.2C4.7 16 3.3 16 2 16c1.1 0 1.5-1.6 1.5-3.5S3.1 9 2 9c1.3 0 2.7 0 3.3 1.2c.2.3.3.8.4 1.2c.3-.7 1-1.4 1.9-1.9L1.1 3l1.3-1.3l19.7 19.7zM9.8 6.6L9 5c2 0 4 0 5.3.7c1.1.6 1.8 1.6 2.4 2.7c2.9.7 5.3 2.3 5.3 4.1c0 1.3-1.2 2.5-3 3.3zM16 12c0 .6.4 1 1 1s1-.4 1-1s-.4-1-1-1s-1 .4-1 1"/>
        </svg>
      </span>
    <% end %>

    <span class="mealplan-form-diet-icon-label">
      <%= diet.label.capitalize %>
    </span>
  </label>
</div>

app/views/meal_plans/empty.html.erb
<div class="text-center m-5">
  <h2>Vous n'avez pas encore créé de menu et de liste de courses...</h2>
  <%= link_to new_meal_plan_path, class: "button-main-flow clickable" do %>
    Créer un menu
  <% end %>
</div>

app/views/meal_plans/new.html.erb
<%= render "shared/navbar_main" %>
<div class="mealplan-new">

  <div class="mealplan-new-title d-flex flex-column align-items-center pt-2 px-4 text-center w-75">
    <h1>Bonjour
      <% if user_signed_in?  %>
        <%= current_user.email.split("@").first.capitalize %>
      <% end %>
      !
    </h1>
    <h2>Planifie tes repas de la semaine en 3 clics...</h2>
  </div>

  <div class="mealplan-form">
    <%= form_with model: @meal_plan do |f| %>

      <div class="mealplan-form-input" data-controller="change-qty" data-change-qty-max-value="<%= MealPlan::MAX_NB_MEAL %>" >
        <%= f.label :nb_meals, "Combien de repas veux-tu planifier ?", class: "mealplan-form-label" %>
        <%= f.hidden_field :nb_meals, data: { "change-qty-target": "nbInput" }, value: 5 %>
        <div class="mealplan-form-nb">
          <i
            class="my-icon-minus-wo-circle mealplan-form-nb-icons clickable-green-plus"
            data-action="click->change-qty#decrease">
          </i>
          <p
            class="mealplan-form-nb-qty"
            data-change-qty-target="nbQty">
            5
          </p>
          <i
            class="my-icon-plus-wo-circle mealplan-form-nb-icons clickable-green-plus"
            data-action="click->change-qty#increase">
          </i>
        </div>
      </div>

      <div class="mealplan-form-input" data-controller="change-qty" data-change-qty-max-value="<%= Meal::MAX_NB_PEOPLE %>" >
        <%= f.label :nb_people, "Combien serez-vous à table ?", class: "mealplan-form-label" %>
        <%= f.hidden_field :nb_people, data: { "change-qty-target": "nbInput" }, value: 1  %>
        <div class="mealplan-form-nb">
          <i
            class="my-icon-minus-wo-circle mealplan-form-nb-icons clickable-green-plus"
            data-action="click->change-qty#decrease">
          </i>
          <p
            class="mealplan-form-nb-qty"
            data-change-qty-target="nbQty">
            1
          </p>
          <i
            class="my-icon-plus-wo-circle mealplan-form-nb-icons clickable-green-plus"
            data-action="click->change-qty#increase">
          </i>
        </div>
      </div>

      <div class="mealplan-form-input mealplan-form-diets d-flex flex-column">
        <p class="mealplan-form-label">As-tu un régime particulier ?</p>
        <div class="mealplan-form-diets">
          <% Diet.all.each do |diet| %>
            <%= render partial: "meal_plans/diet_icons", locals: {diet: diet}%>
          <% end %>
        </div>
      </div>

      <div class="mealplan-form-button button-home-page-container pb-3 clickable">
        <%= f.submit "Crée tes menus", class: "button-home-page" %>
      </div>

    <% end %>
  </div>
  <%= render "shared/navbar_bottom" %>
</div>

app/views/meal_plans/show.html.erb
<%= render "shared/navbar_specific", title: "Ton menu", backlink: new_meal_plan_path  %>

<div data-controller="overlay" class="container d-flex flex-column justify-content-between px-4 py-2 mt-3" style="height: 100vh;">
  <div class="overlay" data-action="click->overlay#hide" data-overlay-target="overlay">
    <div class="overlay-content" data-action="click->overlay#prevent" data-overlay-target="content">
      <%# <button data-action="click->overlay#hide">Close</button> %>
      <div data-overlay-target="mealContent">
        <!-- Meal details will be dynamically inserted here -->
      </div>
    </div>
  </div>

  <div class="cards" data-controller="meal swipe-meal">
    <% @meals.sort.each do |meal| %>
      <div class="card-meal-container" data-meal-id="<%= meal.id %>">
        <div class="card-meal">
          <%#= link_to meal_path(meal) do %>
            <div class="card-meal-image clickable" data-action="click->overlay#show" data-meal-id="<%= meal.id %>">
              <%= image_tag meal.recipe.photo_url, alt: meal.recipe.title %>
            </div>
          <%# end %>

          <div class="card-meal-body">
            <h2 class="overflow-ellipsis"><%= meal.recipe.title.truncate(38) %></h2>
            <div class="card-meal-infos" data-controller="change-qty" data-change-qty-max-value="<%= Meal::MAX_NB_PEOPLE %>">
              <p><strong><i class="my-icon-time"></i></strong> <%= meal.recipe.prep_time %> min </p>
              <%= form_with model: meal, data: {change_qty_target: "form"} do |f| %>
                <div class="card-meal-people" >
                  <%= f.hidden_field :nb_people, data: { change_qty_target: "nbInput" }, value: meal.nb_people %>
                  <i
                  class="my-icon-minus clickable-green-plus"
                  data-action="click->change-qty#decrease">
                  </i>
                  <p class="pb-1">
                    <strong><i class="my-icon-people"></i></strong> <span data-change-qty-target="nbQty"><%= meal.nb_people %></span> pers
                  </p>
                  <i
                    class="my-icon-plus clickable-green-plus"
                    data-action="click->change-qty#increase">
                  </i>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="card-icons">
            <%= link_to replace_meal_path(meal), data: {turbo_method: :patch}, class: "card-swap-icon" do %>
              <i class="my-icon-replace clickable-green-plus"></i>
            <% end %>
          <div class="card-trash-icon">
            <a data-action="click->meal#showDeleteModal" data-meal-id="<%= meal.id %>">
              <i class="my-icon-trash clickable-green-plus"></i>
            </a>
          </div>
        </div>
      </div>
    <% end %>

    <%# modal for the delete confirmation pop up %>
    <div class="modal fade show" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Confirmer la suppression</h5>
            <button type="button" class="btn-close" aria-label="Close" data-action="click->meal#dismiss"></button>
          </div>
          <div class="modal-body">
            Vous êtes sûr de vouloir suprimer cette recette ?
          </div>
          <div class="modal-footer">
            <button type="button" id="deleteBtn" class="btn btn-primary" data-action="click->meal#delete" >Supprimer</button>
            <button type="button" class="btn btn-secondary" data-action="click->meal#dismiss">Annuler</button>
          </div>
        </div>
      </div>
    </div>


  </div>

  <div class="grocery-btn-container d-flex justify-content-center align-items-center py-3 clickable">
    <%= button_to "Crée ta liste de courses", {controller: "grocery_lists", action: "create", meal_plan_id: @meal_plan.id},  class: "button-grocery-form", method: :post %>
  </div>
</div>