config/routes.rb
Rails.application.routes.draw do
  get 'stores/index'
  devise_for :users
  # root to: "meal_plans#new"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :meal_plans, only: [:new, :create, :show] do
    resources :grocery_lists, only: [:create, :index]
  end
  resources :meals, only: [:update, :destroy, :show] do
    member do
      patch "replace"
    end
  end
  resources :grocery_items, only: [:update] do
    member do
      patch "mark_as_bought"
    end
  end
  get "map", to: "grocery_lists#mapping", as: :map
  get "meal_plans_empty", to: "meal_plans#empty", as: :meal_plans_empty
  get "grocery_lists_empty", to: "grocery_lists#empty", as: :grocery_lists_empty
  get "mapping_empty", to: "grocery_lists#empty", as: :mapping_empty
end

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar_bottom.html.erb
<div class="navbar-bottom-hidden-background"></div>
<div class="navbar-bottom">
  <%= link_to new_meal_plan_path do %>
    <% if current_page?(new_meal_plan_path) %>
      <%= svg_tag "home-icon-solid", class: "nav-icon my-icon-home" %>
    <% else %>
      <%= svg_tag "home-icon-outline", class: "nav-icon my-icon-home" %>
    <% end %>
  <% end %>

  <% if user_signed_in? && current_user.meal_plans.any? %>
    <%= link_to meal_plan_path(current_user.meal_plans.last) do %>
      <% if current_page?(meal_plan_path(current_user.meal_plans.last)) %>
        <%= svg_tag "menu-icon-solid", class: "my-icon-menu" %>
      <% else %>
        <%= svg_tag "menu-icon-outline", class: "my-icon-menu" %>
      <% end %>
    <% end %>

    <%= link_to meal_plan_grocery_lists_path(current_user.meal_plans.last) do %>
      <% if current_page?(meal_plan_grocery_lists_path(current_user.meal_plans.last)) %>
        <%= svg_tag "grocery-list-icon-solid", class: "nav-icon my-icon-grocery-list" %>
      <% else %>
        <%= svg_tag "grocery-list-icon-outline", class: "nav-icon my-icon-grocery-list" %>
      <% end %>
    <% end %>

    <%= link_to map_path do %>
      <% if current_page?(map_path) %>
        <%= svg_tag "map-icon-solid", class: "nav-icon my-icon-map" %>
      <% else %>
        <%= svg_tag "map-icon-outline", class: "nav-icon my-icon-map" %>
      <% end %>
    <% end %>

  <% else %>
    <%= link_to meal_plans_empty_path do %>
      <% if current_page?(meal_plans_empty_path) %>
        <%= svg_tag "menu-icon-solid", class: "my-icon-menu" %>
      <% else %>
        <%= svg_tag "menu-icon-outline", class: "my-icon-menu" %>
      <% end %>
    <% end %>

    <%= link_to grocery_lists_empty_path do %>
      <% if current_page?(grocery_lists_empty_path) %>
        <%= svg_tag "grocery-list-icon-solid", class: "nav-icon my-icon-grocery-list" %>
      <% else %>
        <%= svg_tag "grocery-list-icon-outline", class: "nav-icon my-icon-grocery-list" %>
      <% end %>
    <% end %>

    <%= link_to mapping_empty_path do %>
      <% if current_page?(mapping_empty_path) %>
        <%= svg_tag "map-icon-solid", class: "nav-icon my-icon-map" %>
      <% else %>
        <%= svg_tag "map-icon-outline", class: "nav-icon my-icon-map" %>
      <% end %>
    <% end %>

  <% end %>


</div>

app/views/shared/_navbar_main.html.erb
<div class="navbar navbar-light navbar-lewagon-home">
  <div class="container-fluid">
    <%= link_to new_meal_plan_path, class: "navbar-brand clickable" do %>
      <%= image_tag "logo.png", alt: "NiokEat" %>
    <% end %>

    <div class="d-flex pl-4">
      <%= link_to destroy_user_session_path, method: :delete, data: {turbo_method: :delete} do %>
        <i class="my-icon-user clickable"></i>
      <% end %>
      <div style="width: 3vh;"></div>
    </div>
  </div>
</div>

app/views/shared/_navbar_specific.html.erb
<div class="navbar navbar-light navbar-lewagon sticky-top p-2">
  <div class="container-fluid px-3">
    <%= link_to backlink do %>
      <i class="my-icon-back pt-2 clickable-green-plus"></i>
    <% end %>
    <h1 class="d-flex text-center align-items-center pt-3 clickable"><%= title %></h1>
    <%= link_to new_meal_plan_path do %>
      <i class="my-icon-xmark pt-2 clickable-green-plus"></i>
    <% end %>
  </div>
</div>